---
- name: Infoblox config
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - infoblox.nios_modules

  tasks:

    - name: Setting up provider values
      set_fact:
       provider:
        host: 10.255.197.92
        validate_certs: "False"

    - name: configure an A record
      infoblox.nios_modules.nios_a_record:
        name: aap.wwt.com
        ipv4: 10.255.197.89
        comment: this is an optional test comment
        state: present
        provider: "{{ provider }}"
      connection: local
...
