---
- name: Infoblox config
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - infoblox.nios_modules

  tasks:

    - name: Setting up provider values
      set_fact:
       provider:
        host: 10.255.197.92
        validate_certs: "False"

    - name: Configure an ipv4 host record
      infoblox.nios_modules.nios_host_record:
        name: CAT3850
        ipv4:
          - address: 10.255.197.85
        aliases:
          - cat3850.ansible.com
        state: present
        provider: "{{ provider }}"
      connection: local