---
- name: Information module for Device Interface By Ip
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Get Stuff
      register: my_details
      cisco.dnac.device_details_info:
        identifier: 017163-CAT9500.labs.wwtatc.local

    - name: Print stuff out
      ansible.builtin.debug:
        var: my_details
