---
- name: Information module for Device Interface By Ip
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
     - name: Create a device in ISE
       register: result
       cisco.ise.network_device:
         name: con57-17.wwtatc.local
         modelName: CAT3850
         NetworkDeviceIPList:
           - ipaddress: 10.255.197.86
             mask: 32
        # ise_hostname: "{{ise_hostname}}" PROVIDED BY CUSTOM CREDENTIAL
        # ise_username: "{{ise_username}}" PROVIDED BY CUSTOM CREDENTIAL
        # ise_password: "{{ise_password}}" PROVIDED BY CUSTOM CREDENTIAL
         ise_verify: false #PROVIDED BY CUSTOM CREDENTIAL ( True by default, setting to false for POC )
     - name: Print out result
       ansible.builtin.debug:
         var: result
...