---
- name: Gold and load
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Tag the given image as golden and load it on device
      register: goldload_ouput
      cisco.dnac.swim_workflow_manager:
        config:
        - tagging_details:
            image_name: cat9k_iosxe.17.12.01.SPA.bin
            device_role: ACCESS
            device_image_family_name: Cisco Catalyst 9300 Switch
            site_name: Global/USA/San Francisco/BGL_18
            tagging: True