---
- name: Manage operations create, update and delete of the resource TACACS Profile
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create
      cisco.ise.tacacs_profile:
        state: present # absent (to remove )
        description: string
        name: string
        sessionAttributes:
          sessionAttributeList:
          - name: string
            type: string
            value: string

# https://console.redhat.com/ansible/automation-hub/repo/published/cisco/ise/content/module/tacacs_profile/