- name: Update incident ticket in servicenow
  hosts: localhost

  tasks:

    - name: Retrieve requested item ticket sysid
      register: result
      servicenow.itsm.incident_info:
        number: "{{ ticket_number }}"

    - name: Print the result
      ansible.builtin.debug:
        var: result

    # - name: Update the requested item work notes and state in ServiceNow
    #   servicenow.itsm.api:
    #     action: patch
    #     resource: sc_req_item
    #     sys_id: "{{ result.record[0].sys_id }}"
    #     data:
    #       request_state: "{{ request_state | default(omit) }}"
    #       comments: "{{ requested_item_comments }}"
    #       state: "{{ requested_item_state }}"