---
- name: Retrieve requested item ticket sysid
  register: result
  servicenow.itsm.incident_info:
    number: "{{ ticket_number }}"

- name: Resolve the incident
  servicenow.itsm.api:
    action: patch
    resource: incident
    sys_id: "{{ result.records[0].sys_id }}"
    data:
      state: "{{ incident_state }}"
      close_code: "{{ incident_close_code }}"
      close_notes: "{{ incident_close_notes }}"
